name: 更新

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started
    
env:
  TZ: Asia/Shanghai

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Initialization environment
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git subversion git-core wget
          sudo timedatectl set-timezone "$TZ"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

    - name: Syn upstream
      run: |
          cd $GITHUB_WORKSPACE
          chmod +x packages.sh
#          rm -rf `find -maxdepth 1 -type d -name "[!.]*" ! -path "./diy"`
#          git rm -r --cache *

    - name: SSH connection to Actions
      uses: garypang13/debugger-action@master
      if: 1 == 1

    - name: Apply
      run: |
         git add .
         git commit -m "update" || true
         git push
