name: 更新

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started
    
env:
  TZ: Asia/Shanghai

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Initialization environment
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git subversion git-core wget
          sudo timedatectl set-timezone "$TZ"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

    - name: Syn upstream
      run: |
          rm -rf `find -maxdepth 1 -type d -name "[!.]*" ! -path "./diy"`
          git rm -r --cache *
          git clone --depth 1 https://github.com/gdck/luci-app-control-weburl.git
          git clone --depth 1 https://github.com/sensec/luci-app-xlnetacc.git
          git clone --depth 1 https://github.com/sirpdboy/luci-app-autotimeset.git
          git clone --depth 1 https://github.com/BoringCat/luci-app-mentohust
          git clone --depth 1 https://github.com/project-lede/luci-app-godproxy
          git clone --depth 1 https://github.com/tty228/luci-app-serverchan
          git clone --depth 1 https://github.com/BoringCat/luci-app-minieap
          git clone --depth 1 https://github.com/jerrykuku/luci-app-vssr
          git clone --depth 1 https://github.com/ysc3839/luci-proto-minieap
          git clone --depth 1 https://github.com/sirpdboy/luci-app-advanced
          git clone --depth 1 https://github.com/jerrykuku/luci-app-jd-dailybonus
          git clone --depth 1 https://github.com/rufengsuixing/luci-app-syncdial      
          git clone --depth 1 https://github.com/sirpdboy/luci-app-netdata
          git clone --depth 1 https://github.com/sensec/ddns-scripts_aliyun
          git clone --depth 1 https://github.com/KumaTea/MentoHUST-SYSU-Guide
          git clone --depth 1 https://github.com/kongfl888/luci-app-adguardhome
          git clone --depth 1 https://github.com/BCYDTZ/luci-app-UUGameAcc
          git clone --depth 1 https://github.com/garypang13/luci-app-eqos
          git clone --depth 1 https://github.com/riverscn/openwrt-iptvhelper.git 
          svn co https://github.com/kenzok8/openwrt-packages/trunk/AdGuardHome
          svn co https://github.com/brvphoenix/wrtbwmon/trunk/wrtbwmon
          svn co https://github.com/immortalwrt/luci/trunk/applications/luci-app-airwhu
          mv -f my-packages/* ./

    - name: SSH connection to Actions
      uses: garypang13/debugger-action@master
      if: 1 == 0

    - name: Apply
      run: |
         git add .
         git commit -m "update" || true
         git push
