name: ci

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git subversion git-core wget
          sudo timedatectl set-timezone "Asia/Shanghai"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Clone packages
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x packages.sh
          git clone https://github.com/canmengxian/12.git
          cd 12
          rm -Rf *
          git rm --cache *
          $GITHUB_WORKSPACE/packages.sh

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GB1_TOKEN }}
        run: |
          [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/packages
          [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/packages
          cd $GITHUB_WORKSPACE/packages
          git add .
          git commit -m "更新$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --quiet "https://${{ secrets.GB1_TOKEN }}@github.com/canmengxian/12.git" HEAD:packages
